services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USERNAME:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_PORT: 15432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:15432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:?error} -d postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  liquibase-migrations:
    image: liquibase/liquibase:4.29
    depends_on:
      db:
        condition: service_healthy
#    entrypoint: "bash"
#    command:
#      - -c
#      - sleep 100000
    command:
      - --changeLogFile=changelog/changelog-root.yaml
      - --url=jdbc:postgresql://db:15432/postgres
      - --username=postgres
      - --password=postgres
      - --log-level=debug
      - update
    volumes:
      - ./shared/db-migrations/src/main/resources/changelog:/liquibase/changelog
    networks:
      - backend

  app:
    image: moleus/highload-systems-itmo:dev
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL:?error}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME:?error}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:?error}

volumes:
  postgres-data:

networks:
  backend:
