services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USERNAME:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_PORT: 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:15432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:?error} -d postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  liquibase-migrations:
    image: liquibase/liquibase:4.29
    depends_on:
      db:
        condition: service_healthy
    command:
      - --changeLogFile=${DB_CHANGE_LOG_FILE:changelog/changelog-root.yaml}
      - --url=jdbc:postgresql://db:15432/postgres
      - --username=postgres
      - --password=postgres
      - --log-level=debug
      - update
    volumes:
      - ./shared/db-migrations/src/main/resources/changelog:/liquibase/changelog
    networks:
      - backend

  cloud-config:
    image: moleus/highload/cloud-config:dev
    working_dir: /app
    volumes:
      - ~/.ssh/highload-cloud-config-ro:/root/.ssh/id_rsa:ro
      - ./config:/app/config
    environment:
#      SPRING_PROFILES_ACTIVE: cloud
      SPRING_PROFILES_ACTIVE: standalone,native
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: 'pavel/fill-docker-compose-file'
    env_file:
      - .env
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  eureka-server:
    image: moleus/highload/eureka-server:dev
    ports:
      - "8761:8761"
    depends_on:
      cloud-config:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  adoption:
    image: moleus/highload/adoption:dev
    depends_on:
      eureka-server:
        condition: service_healthy
    entrypoint: ["bash"]
    command:
      - -c
      - sleep 1000
    env_file:
      - .env
    networks:
      - backend

  animal:
    image: moleus/highload/animal:dev
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend

  api-gateway:
    image: moleus/highload/api-gateway:dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - backend

  authentication:
    image: moleus/highload/authentication:dev
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    networks:
        - backend

  transaction:
    image: moleus/highload/transaction:dev
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
