# а что на порту 9093?
x-kafka-cluster-envs: &kafka-cluster-envs
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2  # at least 2 replicas should be in sync
  KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
  KAFKA_HEAP_OPTS: "-Xms200m -Xmx300m"

x-medium-jvm-heap-envs: &medium-jvm-heap-envs
  JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:+UseSerialGC -Xss512k -XX:MaxRAM=256m"

services:
  kafka-1:
    environment:
      <<: *kafka-cluster-envs
      KAFKA_CFG_NODE_ID: 1

  kafka-2:
    image: 'bitnami/kafka:3.8.0'
    environment:
      <<: *kafka-cluster-envs
      KAFKA_CFG_NODE_ID: 2
    volumes:
      - kafka-2-data:/bitnami/kafka
    networks:
      - backend

  kafka-3:
    image: 'bitnami/kafka:3.8.0'
    environment:
      <<: *kafka-cluster-envs
      KAFKA_CFG_NODE_ID: 3
    volumes:
      - kafka-3-data:/bitnami/kafka
    networks:
      - backend

  ui:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      <<: *medium-jvm-heap-envs
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka-1:9092"
      KAFKA_CLUSTERS_0_NAME: kafka-1
      KAFKA_CLUSTERS_1_BOOTSTRAP_SERVERS: "kafka-2:9092"
      KAFKA_CLUSTERS_1_NAME: kafka-2
      KAFKA_CLUSTERS_2_BOOTSTRAP_SERVERS: "kafka-3:9092"
      KAFKA_CLUSTERS_2_NAME: kafka-3
      DYNAMIC_CONFIG_ENABLED: 'true'

volumes:
  kafka-2-data:
  kafka-3-data:
