GET http://127.0.0.1:8085/api/v1/adoptions
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3ODMwMDY1MzYsInN1YiI6ImN1c3RvbWVyMyIsImlhdCI6MTcyOTAwNjUzNiwicm9sZSI6IkNVU1RPTUVSIiwidXNlcklkIjo1fQ.SfVQCMlc2i7KW8RUarV18PF7aNx1ZFAxQEKGvUfdnTVOtg5v7A3h8BgpHWNvzkt4LoJMEKa_ymbfif2rsvE-Lg

###
POST http://localhost:8082/api/v1/adoptions/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3ODMwMDU2NTgsInN1YiI6ImN1c3RvbWVyMyIsImlhdCI6MTcyOTAwNTY1OCwicm9sZSI6IkNVU1RPTUVSIiwidXNlcklkIjo1fQ.Wcc6D_vW741kxJ-L9H2rFUAVFNfCIpj4dYajEHd2QWTb9-fN2dAszt3bgCEerK2dhBHKLS9GVd_87cjd0A_0ZQ

###
PATCH http://localhost:8080/api/v1/adoptions
Content-Type: application/json

{
  "id": 1,
  "status": "DENIED"
}

