GET http://localhost:9999/api/v1/adoptions
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MjgzOTYwNjksInN1YiI6ImN1c3RvbWVyMiIsImlhdCI6MTcyODM5NTE2OSwicm9sZSI6IkNVU1RPTUVSIiwidXNlcklkIjo5fQ.fztwEUtZHuGHn-eFmFudE_131aPaxS9VtJJGmZFRaTi7AKmln-FaA8nPk3488k1Gv4HXAsB7h6WLyNwiU1x47g

###
POST http://localhost:8080/api/v1/adoptions/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3MjgzOTYwNjksInN1YiI6ImN1c3RvbWVyMiIsImlhdCI6MTcyODM5NTE2OSwicm9sZSI6IkNVU1RPTUVSIiwidXNlcklkIjo5fQ.fztwEUtZHuGHn-eFmFudE_131aPaxS9VtJJGmZFRaTi7AKmln-FaA8nPk3488k1Gv4HXAsB7h6WLyNwiU1x47g

###
PATCH http://localhost:8080/api/v1/adoptions
Content-Type: application/json

{
  "id": 1,
  "status": "DENIED"
}

