### Add new animal
POST http://localhost:8080/api/v1/animals
Authorization: Bearer {{$auth.token("adoption-manager-auth")}}
Content-Type: application/json

{
  "name": "Барсик2",
  "type": "Кот",
  "gender": "MALE",
  "is_castrated": true,
  "health_status": "HEALTHY"
}

> {%
    client.test("Successfully added new animal", function () {
        client.assert(response.status === 201, "Expected status code to be 201");
        client.assert(response.body.name === "Барсик2", "Expected name to be 'Барсик2'");
        client.assert(response.body.type === "Кот", "Expected type to be 'Кот'");
        client.assert(response.body.gender === "MALE", "Expected type to be 'MALE'");
        client.assert(response.body.is_castrated === true, "Expected is_castrated to be true");
        client.assert(response.body.health_status === "HEALTHY", "Expected health_status to be 'HEALTHY'");
    });
%}


### Get all animals
GET http://localhost:8080/api/v1/animals
Authorization: Bearer {{$auth.token("customer-auth")}}

### Get animal with id 1
GET http://localhost:8080/api/v1/animals/1
Authorization: Bearer {{$auth.token("customer-auth")}}

### Change fields of animal 1
PUT http://localhost:8080/api/v1/animals/1
Authorization: Bearer {{$auth.token("adoption-manager-auth")}}
Content-Type: application/json

{
  "name": "Барсик",
  "type": "Кот",
  "gender": "MALE",
  "is_castrated": true,
  "health_status": "SICK"
}

### Shows that we can't change animal's gender
PUT http://localhost:8080/api/v1/animals/1
Authorization: Bearer {{$auth.token("adoption-manager-auth")}}
Content-Type: application/json

{
  "name": "Барсик",
  "type": "Кот",
  "gender": "FEMALE",
  "is_castrated": true,
  "health_status": "SICK"
}

### Shows that we can't change animal's gender
PUT http://localhost:8080/api/v1/animals/1
Authorization: Bearer {{$auth.token("adoption-manager-auth")}}
Content-Type: application/json

{
  "name": "Барсик",
  "type": "Кот",
  "gender": "MALE",
  "is_castrated": false,
  "health_status": "SICK"
}

### Delete animal that doesn't exist
DELETE http://localhost:8080/api/v1/animals/2
Authorization: Bearer {{$auth.token("adoption-manager-auth")}}

### Delete initial animal
DELETE http://localhost:8080/api/v1/animals/1
Authorization: Bearer {{$auth.token("adoption-manager-auth")}}
