### Add a new purpose
POST http://localhost:8080/api/v1/balances/purposes
Authorization: Bearer {{$auth.token("expense-manager-auth")}}
Content-Type: application/json

{
  "name": "Медикаменты"
}

### Get all purposes
GET http://localhost:8080/api/v1/balances/purposes
Authorization: Bearer {{$auth.token("expense-manager-auth")}}

### Get all balances
GET http://localhost:8080/api/v1/balances
Authorization: Bearer {{$auth.token("expense-manager-auth")}}

### Get balance by ID
GET http://localhost:8080/api/v1/balances/1
Authorization: Bearer {{$auth.token("expense-manager-auth")}}
