###

POST http://highload.duckdns.org/api/v1/balances/purposes
Authorization: Bearer {{$auth.token("expense-manager-auth")}}
Content-Type: application/json

{
  "name": "Корм для собак"
}

###
POST http://highload.duckdns.org/api/v1/adoptions/4
Authorization: Bearer {{$auth.token("expense-manager-auth")}}

