POST http://localhost:8080/api/v1/animals
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbWFuYWdlciIsImV4cCI6MTcyNzE3ODQ2NX0.a-1fnpItLFPEgnDDaWT72SG9sd06IMu7vs7vOGmIrlv8F-fAcFJiCWNdqs1Jq6B_WYjtn_OrzoEDu_-ufdP5cg
Content-Type: application/json

{
  "name": "Барсик2",
  "type": "Кот",
  "gender": "MALE",
  "isCastrated": true,
  "healthStatus": "HEALTHY"
}

###
GET http://localhost:8080/api/v1/animals
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lciIsImV4cCI6MTcyNzE3ODM1NH0.b73ZZd_tzMF2Y-PL8NoRX05VDrVLoXmj3Ei4LCDwF_YQIVu39j6pMoi4MXlj8TQxRgC2rNdAql-vgznzMZWgNw

###

GET http://localhost:8080/api/v1/animals/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lciIsImV4cCI6MTcyNzE3ODM1NH0.b73ZZd_tzMF2Y-PL8NoRX05VDrVLoXmj3Ei4LCDwF_YQIVu39j6pMoi4MXlj8TQxRgC2rNdAql-vgznzMZWgNw

###

PUT http://localhost:8080/api/v1/animals/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbWFuYWdlciIsImV4cCI6MTcyNzE3ODQ2NX0.a-1fnpItLFPEgnDDaWT72SG9sd06IMu7vs7vOGmIrlv8F-fAcFJiCWNdqs1Jq6B_WYjtn_OrzoEDu_-ufdP5cg
Content-Type: application/json

{
  "name": "Барсик",
  "type": "Кот",
  "gender": "MALE",
  "isCastrated": true,
  "healthStatus": "SICK"
}

###

PUT http://localhost:8080/api/v1/animals/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbWFuYWdlciIsImV4cCI6MTcyNzE2ODUxM30.lfgs7EeT0uarhyEHWwq8WP6Nwi4tvZ2tGemaBL1i716Tr5a9f6W8ioVJXMZGikzuqXW0LpyJLQ4gPrY6TU5V7Q
Content-Type: application/json

{
  "name": "Барсик",
  "type": "Кот",
  "gender": "FEMALE",
  "isCastrated": true,
  "healthStatus": "SICK"
}

###

PUT http://localhost:8080/api/v1/animals/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbWFuYWdlciIsImV4cCI6MTcyNzE2ODUxM30.lfgs7EeT0uarhyEHWwq8WP6Nwi4tvZ2tGemaBL1i716Tr5a9f6W8ioVJXMZGikzuqXW0LpyJLQ4gPrY6TU5V7Q
Content-Type: application/json

{
  "name": "Барсик",
  "type": "Кот",
  "gender": "MALE",
  "isCastrated": false,
  "healthStatus": "SICK"
}

###

DELETE http://localhost:8080/api/v1/animals/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbWFuYWdlciIsImV4cCI6MTcyNzE3ODQ2NX0.a-1fnpItLFPEgnDDaWT72SG9sd06IMu7vs7vOGmIrlv8F-fAcFJiCWNdqs1Jq6B_WYjtn_OrzoEDu_-ufdP5cg

###

DELETE http://localhost:8080/api/v1/animals/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbWFuYWdlciIsImV4cCI6MTcyNzE3ODQ2NX0.a-1fnpItLFPEgnDDaWT72SG9sd06IMu7vs7vOGmIrlv8F-fAcFJiCWNdqs1Jq6B_WYjtn_OrzoEDu_-ufdP5cg
