POST http://localhost:8080/api/v1/balances/purposes
Authorization: Bearer {{$auth.token("AUTH_EMANAGER_TOKEN")}}
Content-Type: application/json

{
  "name": "Молочко"
}

###
GET http://localhost:8080/api/v1/balances/purposes
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbWFuYWdlciIsImV4cCI6MTcyNzE3MTIzMn0.5EJHcw9NB6ybQWQ6sDZAZlI09Z9YUCaj7N3O-HZQWEuIsNFSCXLYoRp-VZy7FfqNnOOs0evx18utkxqF9jKTcg
Content-Type: application/json

###
GET http://localhost:8080/api/v1/balances
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbWFuYWdlciIsImV4cCI6MTcyNzE3MTIzMn0.5EJHcw9NB6ybQWQ6sDZAZlI09Z9YUCaj7N3O-HZQWEuIsNFSCXLYoRp-VZy7FfqNnOOs0evx18utkxqF9jKTcg
Content-Type: application/json

###
GET http://localhost:8080/api/v1/balances/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbWFuYWdlciIsImV4cCI6MTcyNzE3MTIzMn0.5EJHcw9NB6ybQWQ6sDZAZlI09Z9YUCaj7N3O-HZQWEuIsNFSCXLYoRp-VZy7FfqNnOOs0evx18utkxqF9jKTcg
Content-Type: application/json
