POST http://localhost:8080/api/v1/transactions/donations
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbWFuYWdlciIsImV4cCI6MTcyNzE3ODU4OH0.jBDR4NVoKozg59D3sz1NeMf38qESH3uoeq38e9NXZODqGUa0-Em2iV2XI7mM1cFryzV0RRi8XiN8TUs1OZKa2g
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjdXN0b21lciIsImV4cCI6MTcyNzE3ODczMX0.mQcz-4phtD8SP9X0yRS4ino1AEwE7jlbnzK1S3s4OtL4-q8caFMktM7YQGhfq8Ext2-KFaRhdh2qZo5x38BIgg
Content-Type: application/json

{
  "purposeId": 1,
  "moneyAmount": 100
}
