image:
  repository: ghcr.io/moleus/highload-systems-itmo/animal
  tag: lab4

nameOverride: animal
fullnameOverride: animal

initContainers:
  - name: liquibase-main
    image: ghcr.io/moleus/highload-systems-itmo/db-init:lab4
    command:
      - bash
      - "-c"
      - |
        liquibase --changeLogFile=/changelog/changelog-root.yaml --url=jdbc:postgresql://$DB_HOST:5432/$POSTGRES_DB --username=$POSTGRES_USER --password=$POSTGRES_PASSWORD --log-level=debug update
    env:
      - name: POSTGRES_DB
        value: postgres
      - name: DB_HOST
        value: db
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
              name: db-secrets
              key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
              name: db-secrets
              key: password

envs:
  - name: SERVER_PORT
    value: "80"
  - name: API_ADDRESS
    value: "highload.duckdns.org"
  - name: CLOUD_CONFIG_HOST
    value: cloud-config
  - name: POSTGRES_DB
    value: postgres
  - name: DB_HOST
    value: db
  - name: DB_PORT
    value: "5432"
  - name: SERVICES_ENDPOINTS_IMAGES
    value: images
  - name: SERVICES_ENDPOINTS_ADOPTION
    value: adoption
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: password
