image:
  repository: ghcr.io/moleus/highload-systems-itmo/api-gateway
  tag: pavel-setup-k8s

nameOverride: api-gateway
fullnameOverride: api-gateway

ingress:
  enabled: true

service:
  type: ClusterIP
  port: 80

envs:
  - name: SERVER_PORT
    value: "80"
  - name: CLOUD_CONFIG_HOST
    value: cloud-config
  - name: EUREKA_HOST
    value: eureka-server
