image:
  repository: ghcr.io/moleus/highload-systems-itmo/balance
  tag: lab4

nameOverride: balance
fullnameOverride: balance

serviceAccountName: "hazelcast"

initContainers:
  - name: liquibase-balance
    # TODO: change tag to lab4
    image: ghcr.io/moleus/highload-systems-itmo/db-balance-init:pavel-deploy-db-balance
    imagePullPolicy: Always
    command:
      - bash
      - "-c"
      - |
        liquibase --changeLogFile=/changelog-balance/changelog-root.yaml --url=jdbc:postgresql://$DB_HOST:5432/$POSTGRES_DB --username=$POSTGRES_USER --password=$POSTGRES_PASSWORD --log-level=debug update
    env:
      - name: POSTGRES_DB
        value: postgres
      - name: DB_HOST
        value: db-balance
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: password

envs:
  #  - name: TRANSACTION_DELAY
  #    value: "10"
  - name: APP_SERVER_PORT
    value: "80"
  - name: API_ADDRESS
    value: "highload.duckdns.org"
  - name: CLOUD_CONFIG_HOST
    value: cloud-config
  - name: EUREKA_HOST
    value: eureka-server
  - name: KAFKA_HOST
    value: "kafka:9092"
  - name: POSTGRES_DB
    value: postgres
  - name: DB_HOST
    value: db
  - name: DB_PORT
    value: "5432"
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: password
