image:
  repository: ghcr.io/moleus/highload/cloud-config

nameOverride: cloud-config
fullnameOverride: cloud-config

volumes:
  - name: ssh-key
    secret:
      secretName: github-deploy-key-ro

volumeMounts:
  - name: ssh-key
    mountPath: /root/.ssh/
    readOnly: true

envs:
  - name: SPRING_PROFILES_ACTIVE
    value: cloud
  - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
    value: 'main'

ports:
  - name: http
    containerPort: 8888
