image:
  repository: postgres
  tag: 15

nameOverride: "db-balance"
fullnameOverride: "db-balance"

service:
  port: 5432

initContainers:
  - name: liquibase
    image: ghcr.io/moleus/highload-systems-itmo/db-init:lab4
    command:
      - liquibase
      - --changeLogFile=changelog/changelog-root.yaml
      - --url=jdbc:postgresql://db:5432/$POSTGRES_DB
      - --username=$POSTGRES_USER
      - --password=$POSTGRES_PASSWORD
      - --log-level=debug
      - update

envs:
  - name: POSTGRES_DB
    value: postgres
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: password
  - name: POSTGRES_PORT
    value: 5432
  - name: POSTGRES_SHARED_BUFFERS
    value: 4MB
  - name: POSTGRES_WAL_BUFFERS
    value: 1MB
  - name: POSTGRES_WORK_MEM
    value: 2MB
