image:
  repository: hazelcast/hazelcast
  tag: 5-jdk21

nameOverride: hazelcast
fullnameOverride: hazelcast

replicaCount: 2

service:
  port: 5701

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"

livenessProbe:
  httpGet:
    path: /hazelcast/health
    port: 5701
  initialDelaySeconds: 100
  periodSeconds: 10
  failureThreshold: 5
  timeoutSeconds: 10
readinessProbe:
  httpGet:
    path: /hazelcast/health
    port: 5701
  initialDelaySeconds: 100
  periodSeconds: 10
  failureThreshold: 5
  timeoutSeconds: 10


serviceAccountName: "hazelcast"

#hazelcast:
#  network:
#    rest-api:
#      enabled: true
#      endpoint-groups:
#        HEALTH_CHECK:
#          enabled: true
envs:
  - name: HZ_NETWORK_RESTAPI_ENABLED
    value: "true"
  - name: HZ_NETWORK_RESTAPI_ENDPOINTGROUPS_HEALTHCHECK_ENABLED
    value: "true"
