image:
  repository: hazelcast/hazelcast
  tag: 5-jdk21

nameOverride: hazelcast
fullnameOverride: hazelcast

replicaCount: 1

service:
  port: 5701

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "400m"

livenessProbe:
  httpGet:
    path: /hazelcast/health
    port: 5701
  initialDelaySeconds: 50
  periodSeconds: 10
  failureThreshold: 5
  timeoutSeconds: 10
readinessProbe:
  httpGet:
    path: /hazelcast/health
    port: 5701
  initialDelaySeconds: 50
  periodSeconds: 10
  failureThreshold: 5
  timeoutSeconds: 10

serviceAccountName: "hazelcast"

envs:
  - name: HZ_NETWORK_RESTAPI_ENABLED
    value: "true"
  - name: HZ_NETWORK_RESTAPI_ENDPOINTGROUPS_HEALTHCHECK_ENABLED
    value: "true"
  - name: HZ_EXECUTORSERVICE_DEFAULT_POOLSIZE
    value: "2"
  - name: HZ_NETWORK_JOIN_KUBERNETES_ENABLED
    value: "true"
  - name: HZ_NETWORK_JOIN_KUBERNETES_NAMESPACE
    value: "dev"
  - name: HZ_NETWORK_JOIN_KUBERNETES_SERVICE_NAME
    value: "hazelcast"
  - name: HZ_NETWORK_JOIN_KUBERNETES_EXPOSEEXTERNALLY
    value: "false"
  - name: HZ_NETWORK_JOIN_MULTICAST_ENABLED
    value: "false"

