image:
  repository: ghcr.io/moleus/highload-systems-itmo/images
  tag: pavel-setup-k8s

nameOverride: images
fullnameOverride: images

initContainers:
  - name: liquibase-main
    image: ghcr.io/moleus/highload-systems-itmo/db-init:pavel-setup-k8s
    command:
      - bash
      - "-c"
      - |
        liquibase --changeLogFile=/changelog/changelog-root.yaml --url=jdbc:postgresql://$DB_HOST:5432/$POSTGRES_DB --username=$POSTGRES_USER --password=$POSTGRES_PASSWORD --log-level=debug update
    env:
      - name: POSTGRES_DB
        value: postgres
      - name: DB_HOST
        value: db
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
              name: db-secrets
              key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
              name: db-secrets
              key: password

envs:
  - name: MINIO_ROOT_USER
    valueFrom:
      secretKeyRef:
        name: minio-secrets
        key: username
  - name: MINIO_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: minio-secrets
        key: password
  - name: MINIO_HOST
    value: minio:9000
  - name: MINIO_SERVICE_PUBLIC_ENDPOINT
    value: http://89.169.129.100:80/images
  - name: SERVER_PORT
    value: "80"
  - name: CLOUD_CONFIG_HOST
    value: cloud-config
  - name: EUREKA_HOST
    value: eureka-server
  - name: POSTGRES_DB
    value: postgres
  - name: DB_HOST
    value: db
  - name: DB_PORT
    value: "5432"
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: username
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secrets
        key: password
