global:
  defaultStorageClass: "local-path"

nameOverride: "kafka"
fullnameOverride: "kafka"

listeners:
  client:
    containerPort: 9092
    protocol: PLAINTEXT
    name: CLIENT
  controller:
    name: CONTROLLER
    containerPort: 9093
  advertisedListeners: "CLIENT://:9092,INTERNAL://:9094"
  securityProtocolMap: "CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT"
  interbroker:
    containerPort: 9094
    protocol: PLAINTEXT
    name: INTERNAL

controller:
  replicaCount: 3
  minId: 100
  heapOpts: -Xmx500m -Xms500m
  persistence:
    size: '1Gi'

  resources:
    limits:
      memory: 800Mi
    requests:
      cpu: 50m
      memory: 500Mi

kraft:
  clusterId: abcdefghijklmnopqrstuv
