# get token for user customer:123 /api/v1/auth/login

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "login": "customer",
  "password": "123"
}


### send get request to get all adoption requests with token "eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiQ1VTVE9NRVIiLCJleHAiOjE3MjcxNjM0OTZ9.exCNc_7tg1bv3aYEyxGDqISG_EAAWLDozLkEvCZsJLHgUoLolwHB2Nf77ngnzGyvaXCL_8Mi3Kap4HU5YmvLlA"

GET http://localhost:8080/api/v1/adoption-requests
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiQ1VTVE9NRVIiLCJleHAiOjE3MjcxNjM0OTZ9.exCNc_7tg1bv3aYEyxGDqISG_EAAWLDozLkEvCZsJLHgUoLolwHB2Nf77ngnzGyvaXCL_8Mi3Kap4HU5YmvLlA