spring:
  application:
    name: adoption-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/postgres
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    web-application-type: reactive

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app.base-url: /api/v1

server:
  port: ${APP_SERVER_PORT:8085}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

debug: true
logging:
  level:
    itmo:
      highload: WARN
    web: WARN
    org:
      springframework:
        security: WARN
        web: WARN
jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}

springdoc:
  api-docs:
    enabled: true
    path: /adoption-api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /adoption-swagger-ui.html
    url: /adoption-api/v3/api-docs