spring:
  application:
    name: adoption-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    web-application-type: reactive

app.base-url: /api/v1

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

debug: true
logging:
  level:
    itmo:
      highload: TRACE
    web: TRACE
    org:
      springframework:
        security: TRACE
        web: TRACE
jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}
