app:
  base-url: /api/v1
spring:
  application:
    name: animal-service
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        max-page-size: 50
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      initial-size: 0
      max-size: 15
      max-idle-time: 300000 # 5 минут
      max-lifetime: 600000 # 10 минут
      validation-query: SELECT 1
      validation-query-timeout: 1000 # 1 секунда
      connection-timeout: 10000 # 10 секунд
      idle-timeout: 300000 # 5 минут
  main:
    allow-bean-definition-overriding: true
server:
  port: ${APP_SERVER_PORT:8086}

api:
  address: ${API_ADDRESS:localhost:8080}

jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs


logging:
  level:
    itmo:
      highload: DEBUG
    web: INFO
    org:
      springframework:
        security: INFO
        web: INFO
        web.cors.reactive.DefaultCorsProcessor: DEBUG
    com.hazelcast: DEBUG

hazelcast:
  client:
    cluster-name: dev
    instance-name: dev-node-1
    network:
      addresses:
        - hazelcast:5701
