app:
  base-url: /api/v1
spring:
  application:
    name: animal-service
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        max-page-size: 50
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/postgres
    # username: ${DB_USERNAME:postgres}
    username: user
    password: ${DB_PASSWORD:postgres}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

server:
  port: ${APP_SERVER_PORT:8086}

jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}
