server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: animal-service
          uri: http://${ANIMAL_LOCALHOST:animal}
          predicates:
            - Path=/api/v1/animals/**,/animal-api-service/**
          filters:
            - RewritePath=/animal-api-service/(?<segment>/?.*), /$\{segment}
        - id: adoption-service
          uri: http://${ADOPTION_LOCALHOST:adoption}
          predicates:
            - Path=/api/v1/adoptions/**,/adoption-api-service/**
          filters:
            - RewritePath=/adoption-api-service/(?<segment>/?.*), /$\{segment}
        - id: transaction-service
          uri: http://${TRANSACTION_LOCALHOST:transaction}
          predicates:
            - Path=/api/v1/transactions/**,/transaction-api-service/**
          filters:
            - RewritePath=/transaction-api-service/(?<segment>/?.*), /$\{segment}
        - id: authentication-service
          uri: http://${AUTH_LOCALHOST:authentication}
          predicates:
            - Path=/api/v1/auth/**,/auth-api-service/**
          filters:
            - RewritePath=/auth-api-service/(?<segment>/?.*), /$\{segment}
        - id: notification-service
          uri: http://${NOTIFICATION_LOCALHOST:notification}
          predicates:
            - Path=/api/v1/notifications/ws/**
          filters:
            - RewritePath=/api/v1/notifications/ws/(?<segment>/?.*), /ws/$\{segment}
        - id: images-service
          uri: http://${IMAGES_LOCALHOST:images}
          predicates:
            - Path=/images-api-service/**
          filters:
            - RewritePath=/images-api-service/(?<segment>/?.*), /$\{segment}
        - id: cdn-minio-endpoint
          uri: http://${MINIO_HOST:localhost:9000}
          predicates:
            - Path=/images/**
          filters:
            - RewritePath=/images/(?<segment>/?.*), /$\{segment}
        - id: balance-service
          uri: http://${BALANCE_LOCALHOST:balance}
          predicates:
            - Path=/api/v1/balances/**,/balances-api-service/**
          filters:
            - RewritePath=/balances-api-service/(?<segment>/?.*), /$\{segment}
    loadbalancer:
      retry:
        enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    urls:
    -   name: gateway-service
        url: /v3/api-docs
    -   name: animal-service
        url: /animal-api-service/v3/api-docs
    -   name: adoption-service
        url: /adoption-api-service/v3/api-docs
    -   name: transaction-service
        url: /transaction-api-service/v3/api-docs
    -   name: auth-service
        url: /auth-api-service/v3/api-docs
    -   name: images-service
        url: /images-api-service/v3/api-docs
    -   name: balance-service
        url: /balance-api-service/v3/api-docs