server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: animal-service
          uri: lb://ANIMAL-SERVICE
          predicates:
            - Path=/api/v1/animals/**,/animal-api-service/**
          filters:
            - RewritePath=/animal-api-service/(?<segment>/?.*), /$\{segment}
        - id: adoption-service
          uri: lb://ADOPTION-SERVICE
          predicates:
            - Path=/api/v1/adoptions/**,/adoption-api-service/**
          filters:
            - RewritePath=/adoption-api-service/(?<segment>/?.*), /$\{segment}
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transactions/**,/transaction-api-service/**
          filters:
            - RewritePath=/transaction-api-service/(?<segment>/?.*), /$\{segment}
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/auth-api-service/**
          filters:
            - RewritePath=/auth-api-service/(?<segment>/?.*), /$\{segment}
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/ws/**
          filters:
            - RewritePath=/api/v1/notifications/ws/(?<segment>/?.*), /ws/$\{segment}
        - id: images-service
          uri: lb://IMAGES-SERVICE
          predicates:
            - Path=/images-api-service/**
          filters:
            - RewritePath=/images-api-service/(?<segment>/?.*), /$\{segment}
      discovery:
        locator:
          enabled: true
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    urls:
    -   name: gateway-service
        url: /v3/api-docs
    -   name: animal-service
        url: /animal-api-service/v3/api-docs
    -   name: adoption-service
        url: /adoption-api-service/v3/api-docs
    -   name: transaction-service
        url: /transaction-api-service/v3/api-docs
    -   name: auth-service
        url: /auth-api-service/v3/api-docs
    -   name: images-service
        url: /images-api-service/v3/api-docs
