spring:
  application:
    name: authentication-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

server:
  port: ${APP_SERVER_PORT:8087}

app:
  base-url: /api/v1
jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}

logging:
  level:
    itmo:
      highload: TRACE
    web: TRACE
    org:
      springframework:
        security: TRACE
        web: TRACE
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/


springdoc:
  api-docs:
    enabled: true
    path: /auth-api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /auth-swagger-ui.html
    url: /auth-api/v3/api-docs
