spring:
  application:
    name: authentication-service
  r2dbc:
    dri
  liquibase:
    enabled: true
    show-summary-output: all
    change-log: classpath:db/changelog/changelog-root.yaml

server:
  port: 8088

app:
  base-url: /api/v1
jwt:
  secret:
    sign: '0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg=='

logging:
  level:
    itmo:
      highload: TRACE
    web: TRACE
    org:
      springframework:
        security: TRACE
        web: TRACE
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
