spring:
  application:
    name: authentication-service
  jpa:
    show-sql: true
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    show-summary-output: all
    change-log: classpath:db/changelog/changelog-root.yaml

server:
  port: 8088

app:
  base-url: /api/v1
