spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
    properties:
      spring.json.trusted.packages: "*"

# TODO почему то игнорирует порт запускается 8080
server:
  port: ${APP_SERVER_PORT:8089}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
