spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: "${KAFKA_HOST:localhost:29092}"
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      new-donation-topic: "new_donation"
      adoption-request-created-topic: "adoption_request_created"
      adoption-request-changed-topic: "adoption_request_changed"

      group-id: "transaction_result_notification_group"
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "itmo.highload.kafka.TransactionResultMessage"
      transaction-result-topic: "transaction_result"
    properties:
      spring.json.trusted.packages: "*"

server:
  port: ${APP_SERVER_PORT:8089}

api:
  address: ${API_ADDRESS:localhost:8080}
