spring:
  application:
    name: transaction-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false

server:
  port: 8086
app.base-url: /api/v1

#logging:
#  level:
#    web: TRACE
#    org.springframework.web: TRACE

jwt:
  secret:
    sign: '0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg=='

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

