spring:
  application:
    name: transaction-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  kafka:
    bootstrap-servers: "${KAFKA_HOST:localhost:29092}"
    admin:
      auto-create: true
    topics:
      - name: new_donation
        partitions: 3
        replicas: 1
      - name: balance_check
        partitions: 3
        replicas: 1
      - name: transaction_result
        partitions: 3
        replicas: 1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      new-donation-topic: "new_donation"
      balance-change-topic: "balance_change"
    consumer:
      group-id: "transaction_result_group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"  # Для доверия всем пакетам
        spring.json.value.default.type: "itmo.highload.kafka.TransactionResultMessage"
      transaction-result-topic: "transaction_result"
server:
  port: ${APP_SERVER_PORT:8088}
app.base-url: /api/v1

jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
