replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: ghcr-registry
nameOverride: ""
fullnameOverride: ""

namespace: "dev"

podAnnotations: {}
podLabels: {}

serviceAccountName: "default"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    memory: 400Mi
  requests:
    cpu: 50m
    memory: 200Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 60
  periodSeconds: 5
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 5

envs:
  - name: CLOUD_CONFIG_HOST
    value: cloud-config
  - name: EUREKA_HOST
    value: eureka-server
