server:
  port: 8080
app:
  base-url: /api/v1
spring:
  datasource:
    url: "jdbc:tc:postgresql:15:///test?TC_TMPFS=/testtmpfs:rw"
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    contexts: test
    change-log: classpath:test-changelog-root.yaml
  mvc:
    log-request-details: true

#added as the data is hardcoded in sql file
jwt:
  secret:
    sign: '0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg=='

logging:
  level:
    web: TRACE
    org.springframework.web: TRACE
    itmo.highload: TRACE
    org:
      apache:
        http: DEBUG
eureka:
  client:
    enabled: false

