server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    group:
      lab2:
        security:
    active: lab2
  cloud:
    gateway:
      routes:
        - id: animal-service
          uri: lb://ANIMAL-SERVICE
          predicates:
            - Path=/api/v1/animals/**
        - id: adoption-service
          uri: lb://ADOPTION-SERVICE
          predicates:
            - Path=/api/v1/adoptions/**
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transactions/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
      discovery:
        locator:
          enabled: true
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
