spring:
  application:
    name: transaction-service
  profiles:
    group:
      lab2: security
    active: lab2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
  liquibase:
    enabled: true
    show-summary-output: all
    change-log: classpath:db/changelog/changelog-root.yaml
  data:
    web:
      pageable:
        max-page-size: 50

#app.base-url: /api/v1

#logging:
#  level:
#    web: TRACE
#    org.springframework.web: TRACE

