# This is a basic workflow to help you get started with Actions

name: detekt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run detekt
      uses: gradle/gradle-build-action@v3
      with:
        arguments: detekt 
        gradle-version: 7.6.4
