# This is a basic workflow to help you get started with Actions

name: detekt

on:
  pull_request:
    branches: [ "main" ]

env:
  JDK_VERSION: 17
  GRADLE_VERSION: 8.10.1
  PGHOST: postgres
  PGPORT: 5432
  PGPASSWORD: postgres
  PGUSER: runner
  PGOPTIONS: '--client-min-messages=warning'

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JDK_VERSION }}
    - name: Run detekt
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: --no-daemon detekt
        gradle-version: ${{ env.GRADLE_VERSION }}
  ci:
    services:
        postgres:
            image: postgres:15
            env:
              POSTGRES_USER: ${{ env.PGUSER }}
              POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
            - 5432:5432
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}
    # - name: Run integration tests
    #   uses: gradle/actions/setup-gradle@v3
    #   with:
    #     # TODO: Separate the integration tests from the unit tests in future
    #     arguments: --no-daemon test
    #     gradle-version: ${{ env.GRADLE_VERSION }}