# This is a basic workflow to help you get started with Actions

name: detekt

on:
  pull_request:
    branches: [ "main" ]

env:
  JDK_VERSION: 17
  GRADLE_VERSION: 8.10.1
  PGHOST: postgres
  PGPORT: 5432
  PGPASSWORD: postgres
  PGUSER: runner
  PGOPTIONS: '--client-min-messages=warning'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JDK_VERSION }}
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: ${{ env.GRADLE_VERSION }}
    - name: Run detekt
      run: detekt
    - name: Run unit & e2e tests
      run: check
