# This is a basic workflow to help you get started with Actions

name: detekt

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

env:
  JDK_VERSION: 17
  GRADLE_VERSION: 8.10.2
  PGHOST: postgres
  PGPORT: 5432
  PGPASSWORD: postgres
  PGUSER: runner
  PGOPTIONS: '--client-min-messages=warning'
  GRADLE_OPTS: -Xmx2048M
  JAVA_OPTS: -Xmx2048M

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JDK_VERSION }}
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
        gradle-version: ${{ env.GRADLE_VERSION }}
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
    - name: Envs
      run: env
    - name: Run detekt
      run: ./gradlew detekt --configuration-cache
    - name: Run unit & e2e tests
      run: ./gradlew check --configuration-cache
    - name: Generate kover coverage report
      run: ./gradlew koverXmlReport
    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: build/reports/
    - name: Add coverage report to PR
      uses: mi-kas/kover-report@5f58465b6f395c8fa3adc2665e27250bad87de50  # v1
      with:
        path: ${{ github.workspace }}/build/reports/kover/report.xml
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 70
        min-coverage-changed-files: 70
        coverage-counter-type: LINE
