name: Deploy services

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the docker images'
        required: false
        default: 'lab4'

permissions:
  contents: read
  pull-requests: write

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start and run
        env:
          LAB_TAG: ${{ github.event.inputs.tag }}
        run: |
          docker compose --env-file env-ci -f docker-compose.yml up -d --wait
