name: Deploy services

on:
  issue_comment:
    types: [ created ]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read

jobs:
  deploy-to-k8s:
    if: ${{ github.event.issue.pull_request }} # only run on pull request comments
    runs-on: ubuntu-latest
    steps:
      - uses: github/branch-deploy@v9.9.1
        id: branch-deploy
        with:
          checks: "required"
          skip_ci: "true"
          trigger: ".deploy"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.K8S_KUBECONFIG_CONTENTS }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy services
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        run: |
          services_to_deploy="${{ steps.branch-deploy.outputs.params }}"
          echo "Deploying services: $services_to_deploy"
          IFS=' ' read -r -a services <<< "$services_to_deploy"
          for service in "${services[@]}"; do
            helm template -f "deploy/${service}-values.yaml" $service | kubectl apply -n dev -f -
          done
