name: Build docker images and push to registry

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  JDK_VERSION: 21
  GRADLE_VERSION: 8.10.2
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"
  REGISTRY: ghcr.io

permissions:
  packages: write
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.read-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Read default version
        id: read-version
        uses: ./.github/actions/read-version

  build-and-push:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          gradle-version: ${{ env.GRADLE_VERSION }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: moleus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        env:
          IMAGE_TAG: ${{ needs.prepare.outputs.tag_version }}
          PUSH_TO_REGISTRY: true
        run: |
          ./gradlew jib

  build-and-push-dockerfile:
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - app: db-init
            dockerfile: ./deploy/db-init.Dockerfile
            build-args: |
              MIGRATIONS_DIR=./shared/db-migrations/src/main/resources/changelog
          - app: db-balance-init
            dockerfile: ./deploy/db-init.Dockerfile
            build-args: |
              MIGRATIONS_DIR=./shared/db-migrations/src/main/resources/changelog-balance
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: moleus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build db-init docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.config.dockerfile }}
          build-args: ${{ matrix.config.build-args }}
          push: true
          tags: ghcr.io/moleus/highload-systems-itmo/${{ matrix.config.app }}:${{ needs.prepare.outputs.tag_version }}
