name: Build docker images and push to registry

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  JDK_VERSION: 21
  GRADLE_VERSION: 8.10.2
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"
  REGISTRY: ghcr.io

permissions:
  packages: write
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.tag.outputs.tag_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Read default version
        id: read-version
        uses: ./.github/actions/read-version
      - name: image tag with branch name
        id: tag
        run: |
          branch_name=${{ env.BRANCH_NAME }}
          tag=${branch_name//\//-}
          if [[ ${{ github.event_name }} == 'push' ]]; then
            tag=${{ steps.read-version.outputs.version }}
          fi
          echo "tag_version=$tag" >> $GITHUB_OUTPUT

  build-and-push:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          gradle-version: ${{ env.GRADLE_VERSION }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: moleus
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        env:
          IMAGE_TAG: ${{ needs.prepare.outputs.tag_version }}
          PUSH_TO_REGISTRY: true
        run: |
          ./gradlew jib
