spring:
  application:
    name: cloud-config

  cloud:
    config:
      server:
        git:
          uri: git@github.com:moleus/highload-systems-itmo.git
          clone-on-start: true
          default-label: main
          search-paths:
            - config

server:
  port: 8888
