spring:
  application:
    name: cloud-config

  cloud:
    config:
      server:
        native:
          search-locations: [classpath:/config/]
#          ${CONFIG_PATH}

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
